### PR TITLE
Added readme for Step 1

### PR DESCRIPTION
**Pull request by chrisahardie**

### CODE REVIEW

**Comment by vivienchevallier** [comment]
As we are providing the solution to start with the webproject, you can remove
- img1.png 
- img2.png 
- img3.png 

And the related parts in the readme

**Comment by chrisahardie** [comment]
@vivienchevallier Can you please confirm exactly where the start point should be?

**Comment by vivienchevallier** [comment]
@chrisahardie Check the snippets: https://github.com/alainvezina/GlobalAzureBootcamp/tree/master/2017/Step%201%20-%20Publishing%20your%20first%20Web%20Apps/Code%20snippets

First step is to add the QueueMessageModel.cs.
Then QueueController.cs 
Then CreateMessage.cshtml
Then deployment

**Comment by chrisahardie** [comment]
@vivienchevallier Removed the unnecessary bits, have a look and let me know if there's anything further.

**Pull request merged**
